version: "3.9"

services:
  mongo:
    image: mongo:6
    container_name: music-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build:
      context: ./backend
      target: production
    container_name: music-backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    environment:
      - NODE_ENV=production
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
      target: production
    container_name: music-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  mongo-data:
