# ---------- Base stage ----------
FROM node:18 AS base
WORKDIR /app
COPY package*.json ./
RUN npm install

# ---------- Development stage ----------
FROM base AS development
COPY . .
ENV NODE_ENV=development
ENV CHOKIDAR_USEPOLLING=true
EXPOSE 5000
CMD ["npm", "run", "dev"]

# ---------- Production stage ----------
FROM base AS production
COPY . .
ENV NODE_ENV=production
RUN npm prune --production
EXPOSE 5000
CMD ["npm", "run", "start"]
